source 'http://gemcutter.org'
source 'http://gems.github.com'
source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'haml'

group :test do
  gem 'autotest'
  gem 'factory_girl'
  gem 'rspec-rails', '>= 2.1.0'
  gem 'cucumber'
  gem 'cucumber-rails'
end
